export const stories = [
    
    {  id: "1", name: "Your story",image: require("../assets/my-story.png")},
    { id: "2", name: "ll.akt.ll", image: require("../assets/userpp/akt-pp.png") },
    { id: "5", name: "kevserzeyrek", image: require("../assets/userpp/tuana-pp.png") },
    { id: "4", name: "eet", image: require("../assets/userpp/eet-pp.png") },
    { id: "3", name: "_mevlude_", image: require("../assets/userpp/mevo-pp.png") },
    { id: "6", name: "ll.akt.ll", image: require("../assets/userpp/akt-pp2.png") },
    { id: "7", name: "emre_ozbek11", image: require("../assets/userpp/ozbek-pp.png") },
    { id: "8", name: "ll.akt.ll", image: require("../assets/userpp/akt-pp3.png") },
    { id: "9", name: "kursadaydogan_", image: require("../assets/userpp/kursad-pp.png") },
    { id: "10", name: "Sezencik", image: require("../assets/userpp/sezen-pp.png") },
    { id: "11", name: "Verder", image: require("../assets/circlee.png") },
    { id: "12", name: "Joshua", image: require("../assets/circlee.png") },
    { id: "13", name: "Alex", image: require("../assets/circlee.png") },
    { id: "14", name: "Volkan", image: require("../assets/circlee.png") },
    { id: "15", name: "JorgeJesus", image: require("../assets/circlee.png") },
    { id: "16", name: "User 16", image: require("../assets/circlee.png") },
    { id: "17", name: "User 17", image: require("../assets/circlee.png") },
    { id: "18", name: "User 18", image: require("../assets/circlee.png") },
    { id: "19", name: "User 19", image: require("../assets/circlee.png") },
    { id: "20", name: "User 20", image: require("../assets/circlee.png") },
    { id: "21", name: "User 21", image: require("../assets/circlee.png") },
    { id: "22", name: "User 22", image: require("../assets/circlee.png") },
    { id: "23", name: "User 23", image: require("../assets/circlee.png") },
    { id: "24", name: "User 24", image: require("../assets/circlee.png") },
    { id: "25", name: "User 25", image: require("../assets/circlee.png") },
    { id: "26", name: "User 26", image: require("../assets/circlee.png") },
    { id: "27", name: "User 27", image: require("../assets/circlee.png") },
    { id: "28", name: "User 28", image: require("../assets/circlee.png") },
    { id: "29", name: "User 29", image: require("../assets/circlee.png") },
    { id: "30", name: "User 30", image: require("../assets/circlee.png") },
  ];