export const item = [
    {
      id: "100",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnak-akt.jpg"),
      likes: "2.834 likes",
      caption: " Tatlış minnak AKT",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "101",
      userpp: require("../assets/kursad.jpg"),
      username: "kursadHd",
      postimage: require("../assets/minnak/balkon-keyfi.jpg"),
      likes: "2.834 likes",
      caption: "ismail abiyle balkon keyfi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "102",
      userpp: require("../assets/userpp-3.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnak-akt-bisiklet.jpg"),
      likes: "2.834 likes",
      caption: " Balkonda bisiklet keyfi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "102",
      userpp: require("../assets/userpp-3.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/sezen/sezen2.jpg"),
      likes: "2.834 likes",
      caption: " Viyk viyk viyk...",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "103",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnak-zeliş.jpg"),
      likes: "2.834 likes",
      caption: "Minnak tatlı cadı Zeliş",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "104",
      userpp: require("../assets/userpp-1.jpg"),
      username: "emre_ozbek11",
      postimage: require("../assets/minnak/minnak-bahadır2.jpg"),
      likes: "2.834 likes",
      caption: " Minnak İsmail abi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "104",
      userpp: require("../assets/userpp-1.jpg"),
      username: "emre_ozbek11",
      postimage: require("../assets/sezen/sezen3.jpg"),
      likes: "2.834 likes",
      caption: " Viyk viyk viyk...",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "105",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/balkon-keyfi2.jpg"),
      likes: "2.834 likes",
      caption: " Yine İsmail abiyle balkon keyfi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "106",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/akt-hala.jpg"),
      likes: "2.834 likes",
      caption: " Küçük halayla şeker toplamaca",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "4234",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnaklar.jpg"),
      likes: "2.834 likes",
      caption: " Minnaklar",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
  
    {
      id: "107",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/top-keyfi.jpg"),
      likes: "2.834 likes",
      caption: " İsmail abiyle evde top oynama keyfi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
  
    {
      id: "2323",
      userpp: require("../assets/userpp-1.jpg"),
      username: "emre_ozbek11",
      postimage: require("../assets/sezen/sezen4.jpg"),
      likes: "2.834 likes",
      caption: " Viyk viyk viyk...",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "2323",
      userpp: require("../assets/userpp-1.jpg"),
      username: "emre_ozbek11",
      postimage: require("../assets/minnak/minnak-bahadır.jpg"),
      likes: "2.834 likes",
      caption: " Başka bir İsmail abi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "108",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnak-zeliş2.jpg"),
      likes: "2.834 likes",
      caption: " Biraz büyümüş mikrop Zeliş",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "109",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnak-akt-acı.jpg"),
      likes: "2.834 likes",
      caption: " Acı çeken AKT",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "1094",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/sezen/sezen1.jpg"),
      likes: "42.941 likes",
      caption: " Viyk viyk viyk...",
      loadTime: " 08.02.2022 ·",
      comments: "View all 43 comments",
    },
    {
      id: "110",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/minnaklar2.jpg"),
      likes: "2.834 likes",
      caption: " Minnak kardeşler karesi",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/userpp-4.jpg"),
      username: "Zeyrekoo",
      postimage: require("../assets/minnak/minnak-akt.jpg"),
      likes: "2.834 likes",
      caption: " Ve minnak tatlış AKT yine",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/minnak/akrabatik-hareketler.gif"),
      likes: "2.834 likes",
      caption: " AKT den akrobatik hareketler",
      loadTime: " 57 minutes ago ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/userpp-1.jpg"),
      username: "ll.akt.ll",
      postimage: require("../assets/sezen/sezen5.jpg"),
      likes: "8.249 likes",
      caption: " Viyk viyk viyk...",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/zafer-pp.jpg"),
      username: "zafer_irenn",
      postimage: require("../assets/zafer.jpg"),
      likes: "3.729 likes",
      caption: " Gönül yorgun düştüğünde, yürek dilsiz kalırmış...🚬🚬",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/durdu.jpg"),
      username: "durdu.atabey",
      postimage: require("../assets/durdu-pp.jpg"),
      likes: "3.729 likes",
      // caption: " Gönül yorgun düştüğünde, yürek dilsiz kalırmış...🚬🚬",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
    {
      id: "111",
      userpp: require("../assets/batu.jpg"),
      username: "batuhann_cngz",
      postimage: require("../assets/batu-pp.jpg"),
      likes: "3.729 likes",
      caption: " ☕️ ☕️",
      loadTime: " 08.02.2022 ·",
      comments: "View all 108 comments",
    },
  ];

  
  